repos:
  - repo: local
    hooks:

      - id: ruff-format
        name: "Format Python (ruff)"
        entry: poetry run ruff format
        language: system
        types: [python]
        pass_filenames: true

      - id: ruff-lint
        name: "Lint Python (ruff)"
        entry: poetry run ruff check
        language: system
        types: [python]
        pass_filenames: true

      - id: mypy
        name: "Type check Python (mypy)"
        entry: poetry run mypy .
        language: system
        pass_filenames: false
        types_or: [python]
        require_serial: true

      - id: check-yaml
        name: Check YAML syntax
        entry: poetry run check-yaml
        language: system
        types: [yaml]

      - id: check-toml
        name: Check TOML syntax
        entry: poetry run check-toml
        language: system
        types: [toml]

      - id: mdformat
        name: Format Markdown files
        entry: poetry run mdformat
        language: system
        types: [markdown]
