repos:
  - repo: local
    hooks:
      - id: check-yaml
        name: Check YAML syntax
        entry: poetry run check-yaml
        language: system
        types: [yaml]

      - id: check-toml
        name: Check TOML syntax
        entry: poetry run check-toml
        language: system
        types: [toml]

      - id: mdformat
        name: Format Markdown files
        entry: poetry run mdformat
        language: system
        types: [markdown]

      - id: ruff-format
        name: "Run 'ruff format' for extremely fast Python formatting"
        entry: uv run ruff format . --exclude=.venv/
        language: system
        types: [python]

      - id: ruff-lint
        name: "Run 'ruff' for extremely fast Python linting"
        entry: poetry run ruff check
        language: system
        types: [python]
        pass_filenames: true

      - id: mypy
        name: mypy
        description: "`mypy` will check Python types for correctness"
        entry: poetry run mypy
        language: system
        pass_filenames: true
        types_or: [python]
        require_serial: true